---
title: "Simple CNN with Keras"
author: "Jurgen de Jager"
date: "July 11, 2017"
output: html_document
---

#Loading Packages
```{r}
# devtools::install_github("rstudio/keras")
library(keras)
# install_tensorflow()
```

#Set Up Direcotries and Specifiy Parameters 
```{r setup, include=FALSE}
train_directory <- "/Users/jdejager/Desktop/git-keras/image_keras/data/train"
validation_directory <- "/Users/jdejager/Desktop/git-keras/image_keras/data/validation"

img_width <- 150
img_height <- 150
batch_size <- 32
epochs <- 30
train_samples = 2048
validation_samples = 832
```

#Loading Images 
```{r}
train_generator <- flow_images_from_directory(train_directory, generator = image_data_generator(),
                                              target_size = c(img_width, img_height), color_mode = "rgb",
                                              class_mode = "binary", batch_size = batch_size, shuffle = TRUE,
                                              seed = 123)


validation_generator <- flow_images_from_directory(validation_directory, generator = image_data_generator(),
                                                   target_size = c(img_width, img_height), color_mode = "rgb", classes = NULL,
                                                   class_mode = "binary", batch_size = batch_size, shuffle = TRUE,
                                                   seed = 123)
```


#Model Architecture
```{r}
model <- keras_model_sequential()
model %>%
  layer_conv_2d(filter = 32, kernel_size = c(3,3), input_shape = c(img_width, img_height, 3)) %>%
  layer_activation("relu") %>%
  layer_max_pooling_2d(pool_size = c(2,2)) %>% 
  
  layer_conv_2d(filter = 32, kernel_size = c(3,3)) %>%
  layer_activation("relu") %>%
  layer_max_pooling_2d(pool_size = c(2,2)) %>%
  
  layer_conv_2d(filter = 64, kernel_size = c(3,3)) %>%
  layer_activation("relu") %>%
  layer_max_pooling_2d(pool_size = c(2,2)) %>%
  
  layer_flatten() %>%
  layer_dense(64) %>%
  layer_activation("relu") %>%
  layer_dropout(0.5) %>%
  layer_dense(1) %>%
  layer_activation("sigmoid")

model %>% compile(
  loss = "binary_crossentropy",
  optimizer = optimizer_rmsprop(lr = 0.0001, decay = 1e-6),
  metrics = "accuracy"
)
```


#Training
```{r}
model %>% fit_generator(
  train_generator,
  steps_per_epoch = as.integer(train_samples/batch_size), 
  epochs = epochs, 
  validation_data = validation_generator,
  validation_steps = as.integer(validation_samples/batch_size),
  verbose=2,
  callback_tensorboard(log_dir = "logs", histogram_freq = 5,
                       write_graph = TRUE, write_images = TRUE, embeddings_freq = 5,
                       embeddings_layer_names = "Jurgen", embeddings_metadata = NULL )
)

```

#Evaluate 
```{r}
evaluate_generator(model,validation_generator, validation_samples)
```

